### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by zaoqi-unsafe** [momocow/node-cq-websocket#42]
Your environment has been set up for using Node.js 10.15.1 (ia32) and npm.

C:\Users\zaoqi>cd bot

C:\Users\zaoqi\bot>node bot.js
[/event] 建立連線中, 請稍後...
[/api] 建立連線中, 請稍後...
/event { SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener (C:\Users\zaoqi\node_modules\cq-websocket\src\index.js:479:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\zaoqi\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:189:13)
    at ClientRequest.handleRequestError (C:\Users\zaoqi\node_modules\websocket\lib\WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8) name: 'SocketError' }
[/event] 連線失敗 。･ﾟ･(つд`ﾟ)･ﾟ･ [丑1] 對噗起
[/event] 連線關閉(1006: connection failed)
/api { SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener (C:\Users\zaoqi\node_modules\cq-websocket\src\index.js:479:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\zaoqi\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:189:13)
    at ClientRequest.handleRequestError (C:\Users\zaoqi\node_modules\websocket\lib\WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8) name: 'SocketError' }
[/api] 連線失敗 。･ﾟ･(つд`ﾟ)･ﾟ･ [丑1] 對噗起
[/api] 連線關閉(1006: connection failed)
[/event] 建立連線中, 請稍後...
[/api] 建立連線中, 請稍後...
/event { SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener (C:\Users\zaoqi\node_modules\cq-websocket\src\index.js:479:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\zaoqi\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:189:13)
    at ClientRequest.handleRequestError (C:\Users\zaoqi\node_modules\websocket\lib\WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8) name: 'SocketError' }
[/event] 連線失敗 。･ﾟ･(つд`ﾟ)･ﾟ･ [丑2] 對噗起
[/event] 連線關閉(1006: connection failed)
/api { SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener (C:\Users\zaoqi\node_modules\cq-websocket\src\index.js:479:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\zaoqi\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:189:13)
    at ClientRequest.handleRequestError (C:\Users\zaoqi\node_modules\websocket\lib\WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8) name: 'SocketError' }
[/api] 連線失敗 。･ﾟ･(つд`ﾟ)･ﾟ･ [丑2] 對噗起
[/api] 連線關閉(1006: connection failed)
[/event] 建立連線中, 請稍後...
[/api] 建立連線中, 請稍後...
/event { SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener (C:\Users\zaoqi\node_modules\cq-websocket\src\index.js:479:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\zaoqi\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:189:13)
    at ClientRequest.handleRequestError (C:\Users\zaoqi\node_modules\websocket\lib\WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8) name: 'SocketError' }
[/event] 連線失敗 。･ﾟ･(つд`ﾟ)･ﾟ･ [丑3] 對噗起
[/event] 連線關閉(1006: connection failed)
/api { SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener (C:\Users\zaoqi\node_modules\cq-websocket\src\index.js:479:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\zaoqi\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (C:\Users\zaoqi\node_modules\websocket\lib\W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:189:13)
    at ClientRequest.handleRequestError (C:\Users\zaoqi\node_modules\websocket\lib\WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8) name: 'SocketError' }
[/api] 連線失敗 。･ﾟ･(つд`ﾟ)･ﾟ･ [丑3] 對噗起
[/api] 連線關閉(1006: connection failed)
^C
C:\Users\zaoqi\bot>

**Comment by zaoqi-unsafe** [comment]
const { CQWebSocket } = require('cq-websocket')
const bot = new CQWebSocket({
    host: "127.0.0.1",
    port: 6700,
    baseUrl: "",
    qq: "2679125746",
    accessToken: ""
  })
  
  // 設定訊息監聽
  bot
    // 連線例外處理
    .on('socket.error', console.error)
    .on('socket.connecting', (wsType) => console.log('[%s] 建立連線中, 請稍後...', wsType))
    .on('socket.connect', (wsType, sock, attempts) => console.log('[%s] 連線成功 ヽ(✿ﾟ▽ﾟ)ノ 蛆蛆%d個嘗試', wsType, attempts))
    .on('socket.failed', (wsType, attempts) => console.log('[%s] 連線失敗 。･ﾟ･(つд`ﾟ)･ﾟ･ [丑%d] 對噗起', wsType, attempts))
    .on('api.response', (resObj) => console.log('伺服器響應: %O', resObj))
    .on('socket.close', (wsType, code, desc) => console.log('[%s] 連線關閉(%d: %s)', wsType, code, desc))
    .on('ready', () => console.log('今天又是複讀複讀的一天 ｡:.ﾟヽ(*´∀`)ﾉﾟ.:｡'))

    // 聽取私人信息
    .on('message.private', (e, context) => {
      console.log('叮咚 ✿')
      console.log(context)
    
      // 以下提供三種方式將原訊息以原路送回
      switch (Date.now() % 3) {
        case 0:
          // 1. 調用 CoolQ HTTP API 之 send_msg 方法
          bot('send_msg', context)
          break
        case 1:
          // 2. 或者透過返回值快速響應
          return context.message
        case 2:
          // 3. 或者透過CQEvent實例，先獲取事件處理權再設置響應訊息
          e.stopPropagation()
          e.setMessage(context.message)
      }
    })
  
  bot.connect()

**Comment by momocow** [comment]
這個項目是依賴酷Q 和 CQHTTP API 插件的，想請問你部屬了嗎?
文檔位置 https://cqhttp.cc/docs/4.7/#/

**Comment by zaoqi-unsafe** [comment]
CQHTTP API开了

**Comment by zaoqi-unsafe** [comment]
{
    "host": "[::]",
    "port": 5700,
    "use_http": true,
    "ws_host": "[::]",
    "ws_port": 6700,
    "use_ws": false,
    "ws_reverse_url": "",
    "ws_reverse_api_url": "",
    "ws_reverse_event_url": "",
    "ws_reverse_reconnect_interval": 3000,
    "ws_reverse_reconnect_on_code_1000": true,
    "use_ws_reverse": false,
    "post_url": "",
    "access_token": "",
    "secret": "",
    "post_message_format": "string",
    "serve_data_files": false,
    "update_source": "github",
    "update_channel": "stable",
    "auto_check_update": false,
    "auto_perform_update": false,
    "show_log_console": false,
    "log_level": "info"
}

**Comment by momocow** [comment]
這個項目與 CQHTTP API 插件是透過正向 ws 通信的，所以你的配置中 `use_ws` 要設置為 `true`

**Comment by zaoqi-unsafe** [comment]
日志里看到HTTP API正常启动了
